### ISSUE TITLE
Not compatible with React 17

### ISSUE THREAD

**Issue by rekrap42** [fritx/react-drag-sizing#1]
When trying to install this to a react 17 app it throws an error since the package is set to use react 16. Can this package be updated to use react 17?
![image](https://user-images.githubusercontent.com/72453531/157466425-61e19186-ea2b-444d-a6ed-0feb8bb7cb01.png)

**Comment by fritx** [comment]
@rekrap42 thank you for pointing this out. You can try 0.2.0 now.

Also, if yarn or pnpm is used to install dependencies, there will be no fatal errors except only warnings.
