### ISSUE TITLE
Children is not assignable to type 'IntrinsicAttributes & DragSizingProps'

### ISSUE THREAD

**Issue by ablaszkiewicz** [fritx/react-drag-sizing#2]
I can't get it to work even for the simplest use cases
![image](https://user-images.githubusercontent.com/54682207/187871080-bb1e1c8d-b4f0-413f-b284-33717f1507a5.png)

**Comment by fritx** [comment]
@ablaszkiewicz hi, that's weird, could you get it to work with the demo?
https://github.com/fritx/react-drag-sizing/blob/master/src/Home.tsx#L86

<img width=400 src=https://user-images.githubusercontent.com/6647633/188312652-763e6305-2222-417e-af60-0d429de6932b.png>

**Comment by fritx** [comment]
what are the versions of the following deps in your project?

```plain
react, react-dom, @types/react, @types/react-dom, typescript, react-size-draging
```

**Comment by fritx** [comment]
@ablaszkiewicz now i'm guessing you are using react18?

https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691

found that `@types/react@18` has changed where `PropsWithChildren` is gone

```ts
// v17
interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;

// v18
interface FunctionComponent<P = {}> {
        (props: P, context?: any): ReactElement<any, any> | null;
```

**Comment by ablaszkiewicz** [comment]
@fritx yep. I am using React 18

**Comment by fritx** [comment]
@ablaszkiewicz thanks for pointing this out.

try `react-drag-sizing@^0.2.1` and let me know if you are done :)

**Comment by ablaszkiewicz** [comment]
Works fine. Thanks
